Fix a bad JSON decode on API error
If an API error occurred, the code would fail to parse the response and
you'd get a JSON decode error instead of the actual error. This change
allows the real error to bubble up.

Before this change any API error left a stacktrace ending in

```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

After this change we can see the real underlying error, for example,
with this 404 error

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": {"error": {"kind": "not_found", "klass": "ActiveRecord::RecordNotFound", "message": "Couldn't find Service with 'id'=80"}}}
```